create database user;
use user;
CREATE TABLE user (
	uid int NOT NULL AUTO_INCREMENT,
    username varchar(255) NOT NULL,
	email varchar(250) unique not null,
    primary key (uid)
);

insert into user (username, email) values ("chris","joshlife333+chris@gmail.com");
insert into user (username, email) values ("swetha","joshlife333+swetha@gmail.com");
insert into user (username, email) values ("nathan","joshlife333+nathan@gmail.com");
insert into user (username, email) values ("kingsley","joshlife333+kingsley@gmail.com");
insert into user (username, email) values ("germaine","joshlife333+germaine@gmail.com");
insert into user (username, email) values ("henry","joshlife333+henry@gmail.com");
insert into user (username, email) values ("zan","joshlife333+zan@gmail.com");
insert into user (username, email) values ("marco","joshlife333+marco@gmail.com");
insert into user (username, email) values ("sathwik","joshlife333+sathwik@gmail.com");
insert into user (username, email) values ("fern","joshlife333+fern@gmail.com");
insert into user (username, email) values ("john","joshlife333+john@gmail.com");
insert into user (username, email) values ("rachel","joshlife333+rachel@gmail.com");
insert into user (username, email) values ("neil","joshlife333+neil@gmail.com");
insert into user (username, email) values ("harry","joshlife333+harry@gmail.com");
insert into user (username, email) values ("spongebob","joshlife333+spongebob@gmail.com");
INSERT INTO user (username, email) VALUES ("mmmilqip", "joshlife333+mmmilqip@gmail.com");
INSERT INTO user (username, email) VALUES ("qgrsfxjc", "joshlife333+qgrsfxjc@gmail.com");
INSERT INTO user (username, email) VALUES ("djfuzgiu", "joshlife333+djfuzgiu@gmail.com");
INSERT INTO user (username, email) VALUES ("unxzqihc", "joshlife333+unxzqihc@gmail.com");
INSERT INTO user (username, email) VALUES ("qthweoqc", "joshlife333+qthweoqc@gmail.com");
INSERT INTO user (username, email) VALUES ("bfglvpjg", "joshlife333+bfglvpjg@gmail.com");
INSERT INTO user (username, email) VALUES ("hqkvyzhj", "joshlife333+hqkvyzhj@gmail.com");
INSERT INTO user (username, email) VALUES ("njjjstpa", "joshlife333+njjjstpa@gmail.com");
INSERT INTO user (username, email) VALUES ("lomcreok", "joshlife333+lomcreok@gmail.com");
INSERT INTO user (username, email) VALUES ("qzfnfvvw", "joshlife333+qzfnfvvw@gmail.com");
INSERT INTO user (username, email) VALUES ("tryfxinc", "joshlife333+tryfxinc@gmail.com");
INSERT INTO user (username, email) VALUES ("itmjfpve", "joshlife333+itmjfpve@gmail.com");
INSERT INTO user (username, email) VALUES ("ohetryul", "joshlife333+ohetryul@gmail.com");
INSERT INTO user (username, email) VALUES ("pehieoyp", "joshlife333+pehieoyp@gmail.com");
INSERT INTO user (username, email) VALUES ("gboxmcqd", "joshlife333+gboxmcqd@gmail.com");
INSERT INTO user (username, email) VALUES ("czcvktna", "joshlife333+czcvktna@gmail.com");
INSERT INTO user (username, email) VALUES ("kozrmfoj", "joshlife333+kozrmfoj@gmail.com");
INSERT INTO user (username, email) VALUES ("idoqsuas", "joshlife333+idoqsuas@gmail.com");
INSERT INTO user (username, email) VALUES ("minebxgu", "joshlife333+minebxgu@gmail.com");
INSERT INTO user (username, email) VALUES ("tuyhsaik", "joshlife333+tuyhsaik@gmail.com");
INSERT INTO user (username, email) VALUES ("zhjinunr", "joshlife333+zhjinunr@gmail.com");
INSERT INTO user (username, email) VALUES ("kkhpxejj", "joshlife333+kkhpxejj@gmail.com");
INSERT INTO user (username, email) VALUES ("keffjhwp", "joshlife333+keffjhwp@gmail.com");
INSERT INTO user (username, email) VALUES ("miwxrpfx", "joshlife333+miwxrpfx@gmail.com");
INSERT INTO user (username, email) VALUES ("tzcdocdr", "joshlife333+tzcdocdr@gmail.com");
INSERT INTO user (username, email) VALUES ("ebvkctej", "joshlife333+ebvkctej@gmail.com");
INSERT INTO user (username, email) VALUES ("gyutmmxj", "joshlife333+gyutmmxj@gmail.com");
INSERT INTO user (username, email) VALUES ("blyvbxom", "joshlife333+blyvbxom@gmail.com");
INSERT INTO user (username, email) VALUES ("vksulume", "joshlife333+vksulume@gmail.com");
INSERT INTO user (username, email) VALUES ("tflxambj", "joshlife333+tflxambj@gmail.com");
INSERT INTO user (username, email) VALUES ("xqsqpuza", "joshlife333+xqsqpuza@gmail.com");
INSERT INTO user (username, email) VALUES ("bhpvszxp", "joshlife333+bhpvszxp@gmail.com");
INSERT INTO user (username, email) VALUES ("welfcvck", "joshlife333+welfcvck@gmail.com");
INSERT INTO user (username, email) VALUES ("jcawuaxc", "joshlife333+jcawuaxc@gmail.com");
INSERT INTO user (username, email) VALUES ("ckvugyxk", "joshlife333+ckvugyxk@gmail.com");
INSERT INTO user (username, email) VALUES ("umxyhggz", "joshlife333+umxyhggz@gmail.com");
INSERT INTO user (username, email) VALUES ("zmextsnt", "joshlife333+zmextsnt@gmail.com");
INSERT INTO user (username, email) VALUES ("jcsrkdbf", "joshlife333+jcsrkdbf@gmail.com");
INSERT INTO user (username, email) VALUES ("tgqcuoxk", "joshlife333+tgqcuoxk@gmail.com");
INSERT INTO user (username, email) VALUES ("nuynvxuv", "joshlife333+nuynvxuv@gmail.com");
INSERT INTO user (username, email) VALUES ("tetrjqvh", "joshlife333+tetrjqvh@gmail.com");
INSERT INTO user (username, email) VALUES ("ifupwpcp", "joshlife333+ifupwpcp@gmail.com");
INSERT INTO user (username, email) VALUES ("dhvjywlt", "joshlife333+dhvjywlt@gmail.com");
INSERT INTO user (username, email) VALUES ("vjkrkfwt", "joshlife333+vjkrkfwt@gmail.com");
INSERT INTO user (username, email) VALUES ("ehsxpizr", "joshlife333+ehsxpizr@gmail.com");
INSERT INTO user (username, email) VALUES ("hjnuluga", "joshlife333+hjnuluga@gmail.com");
INSERT INTO user (username, email) VALUES ("jygdpkzo", "joshlife333+jygdpkzo@gmail.com");
INSERT INTO user (username, email) VALUES ("ookdjlkl", "joshlife333+ookdjlkl@gmail.com");
INSERT INTO user (username, email) VALUES ("vvuqorvs", "joshlife333+vvuqorvs@gmail.com");
INSERT INTO user (username, email) VALUES ("zvrkhgdy", "joshlife333+zvrkhgdy@gmail.com");
INSERT INTO user (username, email) VALUES ("kagslpaa", "joshlife333+kagslpaa@gmail.com");
INSERT INTO user (username, email) VALUES ("vlnocxxk", "joshlife333+vlnocxxk@gmail.com");
INSERT INTO user (username, email) VALUES ("pkdkowuv", "joshlife333+pkdkowuv@gmail.com");
INSERT INTO user (username, email) VALUES ("uhffoupt", "joshlife333+uhffoupt@gmail.com");
INSERT INTO user (username, email) VALUES ("whkficlo", "joshlife333+whkficlo@gmail.com");
INSERT INTO user (username, email) VALUES ("djknheju", "joshlife333+djknheju@gmail.com");
INSERT INTO user (username, email) VALUES ("oahxtiji", "joshlife333+oahxtiji@gmail.com");
INSERT INTO user (username, email) VALUES ("rsfmkuvl", "joshlife333+rsfmkuvl@gmail.com");
INSERT INTO user (username, email) VALUES ("pklbcoku", "joshlife333+pklbcoku@gmail.com");
INSERT INTO user (username, email) VALUES ("ctcmmwlv", "joshlife333+ctcmmwlv@gmail.com");
INSERT INTO user (username, email) VALUES ("vqveptox", "joshlife333+vqveptox@gmail.com");
INSERT INTO user (username, email) VALUES ("fzyzuvnj", "joshlife333+fzyzuvnj@gmail.com");
INSERT INTO user (username, email) VALUES ("gqjtdbyy", "joshlife333+gqjtdbyy@gmail.com");
INSERT INTO user (username, email) VALUES ("sfcbppju", "joshlife333+sfcbppju@gmail.com");
INSERT INTO user (username, email) VALUES ("agtavqgt", "joshlife333+agtavqgt@gmail.com");
INSERT INTO user (username, email) VALUES ("bbirglso", "joshlife333+bbirglso@gmail.com");
INSERT INTO user (username, email) VALUES ("ndbaqzdj", "joshlife333+ndbaqzdj@gmail.com");
INSERT INTO user (username, email) VALUES ("bqpxolbp", "joshlife333+bqpxolbp@gmail.com");
INSERT INTO user (username, email) VALUES ("zpgzwrlx", "joshlife333+zpgzwrlx@gmail.com");
INSERT INTO user (username, email) VALUES ("siyndsrw", "joshlife333+siyndsrw@gmail.com");
INSERT INTO user (username, email) VALUES ("jjkulvgq", "joshlife333+jjkulvgq@gmail.com");
INSERT INTO user (username, email) VALUES ("zefyfcib", "joshlife333+zefyfcib@gmail.com");
INSERT INTO user (username, email) VALUES ("dgzskyls", "joshlife333+dgzskyls@gmail.com");
INSERT INTO user (username, email) VALUES ("uguzuwrj", "joshlife333+uguzuwrj@gmail.com");
INSERT INTO user (username, email) VALUES ("vmeoivud", "joshlife333+vmeoivud@gmail.com");
INSERT INTO user (username, email) VALUES ("xjnfjdom", "joshlife333+xjnfjdom@gmail.com");
INSERT INTO user (username, email) VALUES ("lyhamhps", "joshlife333+lyhamhps@gmail.com");
INSERT INTO user (username, email) VALUES ("vjoyvylo", "joshlife333+vjoyvylo@gmail.com");
INSERT INTO user (username, email) VALUES ("mtbeybau", "joshlife333+mtbeybau@gmail.com");
INSERT INTO user (username, email) VALUES ("lyafqoyf", "joshlife333+lyafqoyf@gmail.com");
INSERT INTO user (username, email) VALUES ("mwfshtab", "joshlife333+mwfshtab@gmail.com");
INSERT INTO user (username, email) VALUES ("qpueirng", "joshlife333+qpueirng@gmail.com");
INSERT INTO user (username, email) VALUES ("hhmpwqai", "joshlife333+hhmpwqai@gmail.com");
INSERT INTO user (username, email) VALUES ("xjxuhqiv", "joshlife333+xjxuhqiv@gmail.com");
INSERT INTO user (username, email) VALUES ("orkeaipc", "joshlife333+orkeaipc@gmail.com");
INSERT INTO user (username, email) VALUES ("mtbiayow", "joshlife333+mtbiayow@gmail.com");
INSERT INTO user (username, email) VALUES ("crxdrynb", "joshlife333+crxdrynb@gmail.com");
INSERT INTO user (username, email) VALUES ("txjcdozd", "joshlife333+txjcdozd@gmail.com");
INSERT INTO user (username, email) VALUES ("sdqyssql", "joshlife333+sdqyssql@gmail.com");
INSERT INTO user (username, email) VALUES ("uejwojye", "joshlife333+uejwojye@gmail.com");
INSERT INTO user (username, email) VALUES ("qhpjxefn", "joshlife333+qhpjxefn@gmail.com");
INSERT INTO user (username, email) VALUES ("lcahowdn", "joshlife333+lcahowdn@gmail.com");
INSERT INTO user (username, email) VALUES ("tcvssbpv", "joshlife333+tcvssbpv@gmail.com");
INSERT INTO user (username, email) VALUES ("dsmlmghs", "joshlife333+dsmlmghs@gmail.com");
INSERT INTO user (username, email) VALUES ("ngcchpfp", "joshlife333+ngcchpfp@gmail.com");
INSERT INTO user (username, email) VALUES ("qctwotig", "joshlife333+qctwotig@gmail.com");
INSERT INTO user (username, email) VALUES ("qpgecujm", "joshlife333+qpgecujm@gmail.com");
INSERT INTO user (username, email) VALUES ("fsjffjyv", "joshlife333+fsjffjyv@gmail.com");
INSERT INTO user (username, email) VALUES ("msjjflvu", "joshlife333+msjjflvu@gmail.com");
INSERT INTO user (username, email) VALUES ("ttzjmgie", "joshlife333+ttzjmgie@gmail.com");
INSERT INTO user (username, email) VALUES ("ffidxyei", "joshlife333+ffidxyei@gmail.com");
INSERT INTO user (username, email) VALUES ("sjmrpzhc", "joshlife333+sjmrpzhc@gmail.com");
INSERT INTO user (username, email) VALUES ("lomtltya", "joshlife333+lomtltya@gmail.com");
INSERT INTO user (username, email) VALUES ("hmktaxvu", "joshlife333+hmktaxvu@gmail.com");
INSERT INTO user (username, email) VALUES ("mbskkwmy", "joshlife333+mbskkwmy@gmail.com");
INSERT INTO user (username, email) VALUES ("odzemqla", "joshlife333+odzemqla@gmail.com");
INSERT INTO user (username, email) VALUES ("pxvmaflb", "joshlife333+pxvmaflb@gmail.com");
INSERT INTO user (username, email) VALUES ("rblpvtxm", "joshlife333+rblpvtxm@gmail.com");
INSERT INTO user (username, email) VALUES ("ifwoufol", "joshlife333+ifwoufol@gmail.com");
INSERT INTO user (username, email) VALUES ("dnqeeggg", "joshlife333+dnqeeggg@gmail.com");
INSERT INTO user (username, email) VALUES ("jolnzqtu", "joshlife333+jolnzqtu@gmail.com");
INSERT INTO user (username, email) VALUES ("cddhfscx", "joshlife333+cddhfscx@gmail.com");
INSERT INTO user (username, email) VALUES ("mnnykxdr", "joshlife333+mnnykxdr@gmail.com");
INSERT INTO user (username, email) VALUES ("tbfqgobb", "joshlife333+tbfqgobb@gmail.com");
INSERT INTO user (username, email) VALUES ("xjidqunv", "joshlife333+xjidqunv@gmail.com");
INSERT INTO user (username, email) VALUES ("ofdutsdp", "joshlife333+ofdutsdp@gmail.com");
INSERT INTO user (username, email) VALUES ("uqcdgzjy", "joshlife333+uqcdgzjy@gmail.com");
INSERT INTO user (username, email) VALUES ("mghcumqt", "joshlife333+mghcumqt@gmail.com");
INSERT INTO user (username, email) VALUES ("afucvnns", "joshlife333+afucvnns@gmail.com");
INSERT INTO user (username, email) VALUES ("ujzjvgks", "joshlife333+ujzjvgks@gmail.com");
INSERT INTO user (username, email) VALUES ("xdycithc", "joshlife333+xdycithc@gmail.com");
INSERT INTO user (username, email) VALUES ("gjvwuhxg", "joshlife333+gjvwuhxg@gmail.com");
INSERT INTO user (username, email) VALUES ("nbugcklh", "joshlife333+nbugcklh@gmail.com");
INSERT INTO user (username, email) VALUES ("vyizljvo", "joshlife333+vyizljvo@gmail.com");
INSERT INTO user (username, email) VALUES ("ccroevzz", "joshlife333+ccroevzz@gmail.com");
INSERT INTO user (username, email) VALUES ("enoyqaqb", "joshlife333+enoyqaqb@gmail.com");
INSERT INTO user (username, email) VALUES ("zrnswwjm", "joshlife333+zrnswwjm@gmail.com");
INSERT INTO user (username, email) VALUES ("vcehhqah", "joshlife333+vcehhqah@gmail.com");
INSERT INTO user (username, email) VALUES ("yfomcety", "joshlife333+yfomcety@gmail.com");
INSERT INTO user (username, email) VALUES ("izsfqmas", "joshlife333+izsfqmas@gmail.com");
INSERT INTO user (username, email) VALUES ("prhdsyfu", "joshlife333+prhdsyfu@gmail.com");
INSERT INTO user (username, email) VALUES ("owemsdfs", "joshlife333+owemsdfs@gmail.com");
INSERT INTO user (username, email) VALUES ("jkkyexmo", "joshlife333+jkkyexmo@gmail.com");
INSERT INTO user (username, email) VALUES ("atfqzrwq", "joshlife333+atfqzrwq@gmail.com");
INSERT INTO user (username, email) VALUES ("laddfwqc", "joshlife333+laddfwqc@gmail.com");
INSERT INTO user (username, email) VALUES ("deagonfa", "joshlife333+deagonfa@gmail.com");
INSERT INTO user (username, email) VALUES ("xmspehno", "joshlife333+xmspehno@gmail.com");
INSERT INTO user (username, email) VALUES ("wntamrcb", "joshlife333+wntamrcb@gmail.com");
INSERT INTO user (username, email) VALUES ("mqfixfer", "joshlife333+mqfixfer@gmail.com");
INSERT INTO user (username, email) VALUES ("fmmpuoer", "joshlife333+fmmpuoer@gmail.com");
INSERT INTO user (username, email) VALUES ("lgkawhwz", "joshlife333+lgkawhwz@gmail.com");
INSERT INTO user (username, email) VALUES ("zqfnhvie", "joshlife333+zqfnhvie@gmail.com");
INSERT INTO user (username, email) VALUES ("vxfqrgqn", "joshlife333+vxfqrgqn@gmail.com");
INSERT INTO user (username, email) VALUES ("radgwezr", "joshlife333+radgwezr@gmail.com");
INSERT INTO user (username, email) VALUES ("nsaplrnj", "joshlife333+nsaplrnj@gmail.com");
INSERT INTO user (username, email) VALUES ("lmyedbzt", "joshlife333+lmyedbzt@gmail.com");
INSERT INTO user (username, email) VALUES ("uipuqhiy", "joshlife333+uipuqhiy@gmail.com");
INSERT INTO user (username, email) VALUES ("qdjxdwci", "joshlife333+qdjxdwci@gmail.com");
INSERT INTO user (username, email) VALUES ("xgqasduo", "joshlife333+xgqasduo@gmail.com");
INSERT INTO user (username, email) VALUES ("xbcakcme", "joshlife333+xbcakcme@gmail.com");
INSERT INTO user (username, email) VALUES ("ndnftogs", "joshlife333+ndnftogs@gmail.com");
INSERT INTO user (username, email) VALUES ("spfsuzbk", "joshlife333+spfsuzbk@gmail.com");
INSERT INTO user (username, email) VALUES ("evnhjnsk", "joshlife333+evnhjnsk@gmail.com");
INSERT INTO user (username, email) VALUES ("ipvnkklq", "joshlife333+ipvnkklq@gmail.com");
INSERT INTO user (username, email) VALUES ("zaktobos", "joshlife333+zaktobos@gmail.com");
INSERT INTO user (username, email) VALUES ("hmbnkimb", "joshlife333+hmbnkimb@gmail.com");
INSERT INTO user (username, email) VALUES ("qdkyphgq", "joshlife333+qdkyphgq@gmail.com");
INSERT INTO user (username, email) VALUES ("glikqapq", "joshlife333+glikqapq@gmail.com");
INSERT INTO user (username, email) VALUES ("obljqmeb", "joshlife333+obljqmeb@gmail.com");
INSERT INTO user (username, email) VALUES ("smudbtzh", "joshlife333+smudbtzh@gmail.com");
INSERT INTO user (username, email) VALUES ("zhugutnc", "joshlife333+zhugutnc@gmail.com");
INSERT INTO user (username, email) VALUES ("uspigdmi", "joshlife333+uspigdmi@gmail.com");
INSERT INTO user (username, email) VALUES ("jslfpxgh", "joshlife333+jslfpxgh@gmail.com");
INSERT INTO user (username, email) VALUES ("unentltx", "joshlife333+unentltx@gmail.com");
INSERT INTO user (username, email) VALUES ("zfffihov", "joshlife333+zfffihov@gmail.com");
INSERT INTO user (username, email) VALUES ("gsgepkkr", "joshlife333+gsgepkkr@gmail.com");
INSERT INTO user (username, email) VALUES ("wynobpkb", "joshlife333+wynobpkb@gmail.com");
INSERT INTO user (username, email) VALUES ("tpgzqsqh", "joshlife333+tpgzqsqh@gmail.com");
INSERT INTO user (username, email) VALUES ("knvcwxsa", "joshlife333+knvcwxsa@gmail.com");
INSERT INTO user (username, email) VALUES ("dvzntbzv", "joshlife333+dvzntbzv@gmail.com");
INSERT INTO user (username, email) VALUES ("ecjeghav", "joshlife333+ecjeghav@gmail.com");
INSERT INTO user (username, email) VALUES ("kyohhhtj", "joshlife333+kyohhhtj@gmail.com");
INSERT INTO user (username, email) VALUES ("bmyovesk", "joshlife333+bmyovesk@gmail.com");
INSERT INTO user (username, email) VALUES ("ynozsehg", "joshlife333+ynozsehg@gmail.com");
INSERT INTO user (username, email) VALUES ("ozhsrwtp", "joshlife333+ozhsrwtp@gmail.com");
INSERT INTO user (username, email) VALUES ("pjuqcnop", "joshlife333+pjuqcnop@gmail.com");
INSERT INTO user (username, email) VALUES ("dqlolzcw", "joshlife333+dqlolzcw@gmail.com");
INSERT INTO user (username, email) VALUES ("igdtdgpw", "joshlife333+igdtdgpw@gmail.com");
INSERT INTO user (username, email) VALUES ("ahdcmmlt", "joshlife333+ahdcmmlt@gmail.com");
INSERT INTO user (username, email) VALUES ("ifvvexld", "joshlife333+ifvvexld@gmail.com");
INSERT INTO user (username, email) VALUES ("ritrlahc", "joshlife333+ritrlahc@gmail.com");
INSERT INTO user (username, email) VALUES ("ucleaotb", "joshlife333+ucleaotb@gmail.com");
INSERT INTO user (username, email) VALUES ("paqreuoz", "joshlife333+paqreuoz@gmail.com");
INSERT INTO user (username, email) VALUES ("zdjiagts", "joshlife333+zdjiagts@gmail.com");
INSERT INTO user (username, email) VALUES ("yefnfsta", "joshlife333+yefnfsta@gmail.com");
INSERT INTO user (username, email) VALUES ("cwbfpdoy", "joshlife333+cwbfpdoy@gmail.com");
INSERT INTO user (username, email) VALUES ("pyzadaqy", "joshlife333+pyzadaqy@gmail.com");
INSERT INTO user (username, email) VALUES ("ooqjlrsh", "joshlife333+ooqjlrsh@gmail.com");
INSERT INTO user (username, email) VALUES ("gfirteit", "joshlife333+gfirteit@gmail.com");
INSERT INTO user (username, email) VALUES ("dldbvyww", "joshlife333+dldbvyww@gmail.com");
INSERT INTO user (username, email) VALUES ("jwhgqnkl", "joshlife333+jwhgqnkl@gmail.com");
INSERT INTO user (username, email) VALUES ("zicouumd", "joshlife333+zicouumd@gmail.com");
INSERT INTO user (username, email) VALUES ("ktqichxi", "joshlife333+ktqichxi@gmail.com");
INSERT INTO user (username, email) VALUES ("vlygnlcm", "joshlife333+vlygnlcm@gmail.com");
INSERT INTO user (username, email) VALUES ("opvzbmxv", "joshlife333+opvzbmxv@gmail.com");
INSERT INTO user (username, email) VALUES ("amqunkbj", "joshlife333+amqunkbj@gmail.com");
INSERT INTO user (username, email) VALUES ("yryypwaa", "joshlife333+yryypwaa@gmail.com");
INSERT INTO user (username, email) VALUES ("woktgqic", "joshlife333+woktgqic@gmail.com");
INSERT INTO user (username, email) VALUES ("pmkdtbct", "joshlife333+pmkdtbct@gmail.com");
INSERT INTO user (username, email) VALUES ("anufhtve", "joshlife333+anufhtve@gmail.com");

